version: '3.3'
services:
  areospike-server:
    image: aerospike/aerospike-server 
    container_name: aerospike
    ports:
      - '3000-3002:3000-3002'
  go-server:
    build:
      context: ./
      dockerfile: deploy/Dockerfile
    container_name: go-web-server
    restart: always
    ports:
      - '8000:8080'
