version: '3'
services:
  areospike-server:
    image: aerospike/aerospike-server 
    container_name: aerospike
  go-server:
    build: .
    container_name: go-web-server
    restart: always
    ports:
      - '8000:8080'
